spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://locahost:8081/
          predicates :
            - Path= /customers/**
        - id : r2
          uri : http://locahost:8082/
          predicates :
            - Path= /products/**
    discovery:
      enabled: false
server:
  port: 8888